edy_dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Position Controllers ----------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_1
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_2
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_3
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_4
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_5
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_6
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_7
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_8_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_joint_8
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_9_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_1
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_10_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_2
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_11_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_3
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_12_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_4
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_13_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_5
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_14_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_6
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_15_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_7
    pid: {p: 10, i: 0.01, d: 0.0}

  joint_16_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_joint_8
    pid: {p: 10, i: 0.01, d: 0.0}
